name: Update Releases

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write # Allows the bot to write to repository contents (commits, pull requests)

jobs:
  update-releases:
    runs-on: ubuntu-22.04 # You can adjust the runner version if necessary

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x # Use Python 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install necessary packages

      - name: Set up GitHub Token for API requests
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
        # This ensures the GITHUB_TOKEN is available to the Python script

      - name: Update releases.json
        run: python scripts/generate_releases_json.py # Path to your Python script

      - name: Commit changes to releases.json
        run: |
          git config --global user.email "git@rafsunx.com"  # Replace with your email
          git config --global user.name "RAFSuNX"  # Replace with your name
          git add src/data/releases.json  # Add the updated releases.json
          git commit -m "Update releases.json"  # Commit the changes
          git push origin main  # Push changes to the repository (adjust branch if needed)
