name: Update Releases JSON

on:
  schedule:
    - cron: "0 0 * * *" # This runs the workflow every 24 hours (UTC time)
  workflow_dispatch: # Allows you to manually trigger the workflow from GitHub Actions UI

jobs:
  update-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # You can use any version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the Python script to update releases.json
        run: |
          python scripts/generate_releases_json.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/data/releases.json
          git commit -m "Update releases.json"
          git push
